@startuml Sequence

actor Member
Participant Library
Participant Bill

Member -> Library : Borrow()
Member <- Library : LendBook()

Member -> Library : Return()
Member <- Library : ReturnBook()

Member -> Bill : Pay(amount)
Member <- Bill : Pay(amount)

@enduml