@startuml class-architecture

skinparam groupInheritance 4

enum 2DMove {
    Up
    Down
    Left
    Right
}

interface IPosition {

}

interface IPosition2D extends IPosition {
    + <<get>> x: int
    + <<get>> y: int
}

interface IPlayer {
    + <<get>> Id: Guid
    + <<get>> Name: string
    + <<get>> Email: string
}

interface IPlayer2D extends IPlayer {
    + MoveUp(direction: 2DMove): void
}

interface ILabyrinth2D {
    + <<get>> SizeX: int
    + <<get>> SizeY: int 
    + <<get>> Players: List<IPlayer2D>
    + <<get>> Floors: List<IFloor2D>
    + <<get>> Walls: List<IWall2D>
}

interface ILabyrinthElement2D {
    + <<get>> Position: IPosition2D 
}


abstract A2DLabyrinthElement implements ILabyrinthElement2D {
    + <<get>> Position: IPosition2D 
}

interface IWall2D extends ILabyrinthElement2D {
    + <<get>> Position: IPosition2D 
}

interface IFloor2D extends ILabyrinthElement2D {
    + <<get>> Position: IPosition2D 
}

class Wall2D implements IWall2D {
}

class Floor2D implements IFloor2D {
}

ILabyrinthElement2D *-- IPosition2D
IPlayer2D --|> ILabyrinthElement2D
Wall2D --|> A2DLabyrinthElement
Floor2D --|> A2DLabyrinthElement
ILabyrinth2D "1" *-- "0..many" IPlayer2D

@enduml