@startuml Library (id=LIBRARY) 

interface IBookSource {
	+ Books: IEnumerable<ILibraryBook>
	+ StoreNewBook(book: ILibraryBook): void
	+ GiveAway(book: ILibraryBook): void
	+ SearchInBooks(query: string): ILibraryBook
}

class OnlineBooks implements IBookSource{
	+ Books: IEnumerable<ILibraryBook>
	+ StoreNewBook(book: ILibraryBook): void
	+ GiveAway(book: ILibraryBook): void
	+ SearchInBooks(query: string): ILibraryBook
}

class PhisycalBooks implements IBookSource{
	+ Books: IEnumerable<ILibraryBook>
	+ StoreNewBook(book: ILibraryBook): void
	+ GiveAway(book: ILibraryBook): void
	+ SearchInBooks(query: string): ILibraryBook
}

!startsub Rec
interface ILibrary{
	+ Id: Guid
	+ AllBooks: IList<IBook>
	+ LendBook(member: IMember, book: IBook): void
	+ ReturnBook(member: IMember, book: ILibraryBook): void
	+ ReturnBooks(member: IMember, books: IEnumerable<ILibraryBook>): void
	+ GetNewBook(book: IBook, category: string): void
	+ Register(name: string, username: string, bornAt: DateTime): void
	+ Register(member: IMember): void
}

interface IMember{
	+ Name: string
	+ UserName: string
	+ BornAt: Date
	+ PendingBills: IList<IBill>
	+ BorrowedBooks: IEnumerable<ILibraryBook>
	+ Borrow(book: ILibraryBook): void
	+ Return(book: ILibraryBook): void
	+ Pay(): void
}

!endsub


class LibraryClass{
	- _borrowedBooks: IList<ILibraryBook>
	- SearchBook(isbn: string, target: IEnumerable<ILibraryBook>): ILibraryBook
	- _bookFactory: IBookFactory
	- _members: IList<IMember>
	+ Id: Guid
	+ AllBooks: IList<IBook>
	+ LendBook(member: IMember, book: IBook): void
	+ ReturnBook(member: IMember, book: ILibraryBook): void
	+ ReturnBooks(member: IMember, books: IEnumerable<ILibraryBook>): void
	+ GetNewBook(book: IBook, category: string): void
	+ Register(name: string, username: string, bornAt: DateTime): void
	+ Register(member: IMember): void
}

class Member{
	- _lib: ILibrary
	- _borrowedBooks: IList<ILibraryBook>
	+ Name: string
	+ UserName: string
	+ BornAt: Date
	+ PendingBills: IList<IBill>
	+ BorrowedBooks: IEnumerable<ILibraryBook>
	+ Borrow(book: ILibraryBook): void
	+ Return(book: ILibraryBook): void
	+ Pay(): void
}

ILibrary <.. LibraryClass
ILibrary "0..1" *-- "*" IMember : Registers >
IMember <.. Member

@enduml