@startuml Stack
class Stack {
    -head: Node
    +push(val: int): void
    +pop(): int
    +top(): int
    +isEmpty(): bool
}

class Node {
    -val: int
    -next: Node
    +Node(val: int)
}

Stack -> Node

@enduml